spring:
  datasource:
    url: jdbc:mysql://localhost/test?verifyServerCertificate=false&useSSL=false&requireSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: cecil1018
    password:

logging:
  level:
    org:
      springframework:
        jdbc:
          core: DEBUG
log4j:
  logger:
    org:
      hibernate:
        type: trace
        SQL: debug